Update main.yml
Modificação de arquivo

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -13,16 +13,6 @@ jobs:
     steps:
       - name: 🚚 Get latest code
         uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16'
-
-      - name: 🔨 Build Project
-        run: |
-          npm install
-          npm run build
       
       - name: 📂 Upload build files to cPanel via FTP
         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
@@ -38,7 +28,7 @@ jobs:
             **/.git*/**
 
       - name: Clear cache (optional)
-        run: curl -X GET http://marcostavares.dev.br/?clear_cache=true || echo "Cache clearing failed, but continuing..."
+        run: curl -X GET http://erpress.com.br/?clear_cache=true || echo "Cache clearing failed, but continuing..."
 
       - name: Test FTP Connection
         run: |
